/**
 * Permission Seed SQL Generator
 *
 * Generates SQL INSERT statements for permissions based on generated endpoints
 */

export interface PermissionSeedOptions {
  resourceName: string;
  schema?: string;
  description?: string;
  category?: string;
}

export class PermissionSeedGenerator {
  /**
   * Generate permission seed SQL for CRUD operations
   */
  generateCrudPermissions(options: PermissionSeedOptions): string {
    const { resourceName, schema = 'rbac', description, category } = options;

    const permissions = [
      {
        code: `${resourceName}.create`,
        name: `Create ${resourceName}`,
        description: description
          ? `Create new ${description}`
          : `Permission to create new ${resourceName}`,
        category: category || resourceName,
      },
      {
        code: `${resourceName}.read`,
        name: `Read ${resourceName}`,
        description: description
          ? `View ${description}`
          : `Permission to view ${resourceName} records`,
        category: category || resourceName,
      },
      {
        code: `${resourceName}.update`,
        name: `Update ${resourceName}`,
        description: description
          ? `Edit ${description}`
          : `Permission to update ${resourceName} records`,
        category: category || resourceName,
      },
      {
        code: `${resourceName}.delete`,
        name: `Delete ${resourceName}`,
        description: description
          ? `Remove ${description}`
          : `Permission to delete ${resourceName} records`,
        category: category || resourceName,
      },
    ];

    return this.generateInsertStatements(permissions, schema);
  }

  /**
   * Generate permission seed SQL for custom permissions
   */
  generateCustomPermissions(
    permissions: Array<{
      code: string;
      name: string;
      description: string;
      category: string;
    }>,
    schema: string = 'rbac',
  ): string {
    return this.generateInsertStatements(permissions, schema);
  }

  /**
   * Generate INSERT statements
   */
  private generateInsertStatements(
    permissions: Array<{
      code: string;
      name: string;
      description: string;
      category: string;
    }>,
    schema: string,
  ): string {
    const inserts = permissions.map((perm) => {
      return `INSERT INTO ${schema}.permissions (code, name, description, category, is_active)
VALUES ('${perm.code}', '${perm.name}', '${perm.description}', '${perm.category}', true)
ON CONFLICT (code) DO UPDATE
SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  is_active = EXCLUDED.is_active,
  updated_at = NOW();`;
    });

    const comment = `-- ${permissions[0].category} Permissions
-- Auto-generated by nest-generator
-- Generated at: ${new Date().toISOString()}
`;

    return comment + '\n' + inserts.join('\n\n');
  }

  /**
   * Generate permission seed SQL for complete module (CRUD + custom endpoints)
   */
  generateModulePermissions(
    resourceName: string,
    customEndpoints: Array<{
      action: string;
      name: string;
      description: string;
    }> = [],
    schema: string = 'rbac',
  ): string {
    // Generate CRUD permissions
    const crudSql = this.generateCrudPermissions({ resourceName, schema });

    // Generate custom endpoint permissions
    if (customEndpoints.length === 0) {
      return crudSql;
    }

    const customPermissions = customEndpoints.map((endpoint) => ({
      code: `${resourceName}.${endpoint.action}`,
      name: endpoint.name,
      description: endpoint.description,
      category: resourceName,
    }));

    const customSql = this.generateCustomPermissions(customPermissions, schema);

    return `${crudSql}\n\n-- Custom Endpoint Permissions\n${customSql}`;
  }

  /**
   * Generate role-permission mapping SQL
   */
  generateRolePermissions(
    roleCode: string,
    permissions: string[],
    schema: string = 'rbac',
  ): string {
    const inserts = permissions.map((permCode) => {
      return `INSERT INTO ${schema}.role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM ${schema}.roles r, ${schema}.permissions p
WHERE r.code = '${roleCode}' AND p.code = '${permCode}'
ON CONFLICT (role_id, permission_id) DO NOTHING;`;
    });

    const comment = `-- Role-Permission Mapping for: ${roleCode}
-- Generated at: ${new Date().toISOString()}
`;

    return comment + '\n' + inserts.join('\n\n');
  }

  /**
   * Generate complete permission setup SQL (permissions + role mappings)
   */
  generateCompleteSetup(
    resourceName: string,
    options: {
      customEndpoints?: Array<{
        action: string;
        name: string;
        description: string;
      }>;
      roleMappings?: Array<{
        roleCode: string;
        permissions: string[];
      }>;
      schema?: string;
    } = {},
  ): string {
    const { customEndpoints = [], roleMappings = [], schema = 'rbac' } = options;

    // Generate permission INSERT statements
    const permissionsSql = this.generateModulePermissions(resourceName, customEndpoints, schema);

    if (roleMappings.length === 0) {
      return permissionsSql;
    }

    // Generate role-permission mappings
    const mappingsSql = roleMappings
      .map((mapping) => this.generateRolePermissions(mapping.roleCode, mapping.permissions, schema))
      .join('\n\n');

    return `${permissionsSql}\n\n-- ========================================
-- Role-Permission Mappings
-- ========================================\n\n${mappingsSql}`;
  }
}
